### ISSUE TITLE
v0.6 crashes on patient chart activity

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#156]
Testing client release 0.6 on server 0.6 (running on Edison with buendia-demo configuration).

App installed from Jenkins client-master build http://jenkins.projectbuendia.org/job/client-master/37/

Steps to reproduce:
1. Uninstall other version of app
2. Install app
3. Set server in settings and hit "Apply and clear local data"
4. Log in as Guest User (the only user)
5. There are no patients. Add a patient. First one I tried I entered Prefix, ID, Given Name, Family Name. Second one I tried I entered all the fields.
6. After the patient is added the toast "Patient added" came up
7. App crashed (presumably as it is loading the patient chart)

It also crashes when trying to open a patient chart from the patient list.

Bug reports:
https://www.dropbox.com/s/taa56ifghecph10/bugreport-2015-11-25-16-30-13.txt?dl=0
https://www.dropbox.com/s/q4hix67vpbqtgmf/bugreport-2015-11-25-16-32-41.txt?dl=0

**Comment by llvasconcellos** [comment]
I just downloaded buendia-client-master-0.6.0.apk, tested it and I could not reproduce the problem.
I noticed some differences though. 
First: There where all the users and not only guest. I used "dev.projectbuendia.org". 
Second: The application started with an error connecting to server (red toast) and then, after clearing the data everything worked fine.

**Comment by llvasconcellos** [comment]
This is an Exception extracted from the bug report:

``` java
11-25 16:29:57.185 32162 32162 E AndroidRuntime: FATAL EXCEPTION: main
11-25 16:29:57.185 32162 32162 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 32162
11-25 16:29:57.185 32162 32162 E AndroidRuntime: java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:111)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:268)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:241)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:254)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at com.mitchellbosecke.pebble.loader.FileLoader.<clinit>(FileLoader.java:34)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at com.mitchellbosecke.pebble.PebbleEngine.<init>(PebbleEngine.java:128)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at com.mitchellbosecke.pebble.PebbleEngine.<init>(PebbleEngine.java:114)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.renderTemplate(ChartRenderer.java:273)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.getHtml(ChartRenderer.java:245)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.ChartRenderer.render(ChartRenderer.java:89)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.PatientChartActivity$Ui.updateTilesAndGrid(PatientChartActivity.java:398)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.PatientChartController.updatePatientObsUi(PatientChartController.java:505)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.PatientChartController.access$900(PatientChartController.java:68)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at org.projectbuendia.client.ui.chart.PatientChartController$EventSubscriber$1.run(PatientChartController.java:627)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:733)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:212)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5137)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:515)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
11-25 16:29:57.185 32162 32162 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
11-25 16:29:57.185   910  1243 D ActivityManager: New dropbox entry: org.projectbuendia.client.dev, data_app_crash, e2534a34-823a-4a12-a92b-82a3cbb1e4bf
11-25 16:29:57.185   910  1243 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.chart.PatientChartActivity
11-25 16:29:57.195   910  1243 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.lists.LocationListActivity
```

**Comment by llvasconcellos** [comment]
Another one:

``` java
11-25 16:31:01.235  2580  2580 E AndroidRuntime: FATAL EXCEPTION: main
11-25 16:31:01.235  2580  2580 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 2580
11-25 16:31:01.235  2580  2580 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.projectbuendia.client.dev/org.projectbuendia.client.ui.lists.LocationListActivity}: java.lang.NullPointerException
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:212)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5137)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:515)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
11-25 16:31:01.235  2580  2580 E AndroidRuntime: Caused by: java.lang.NullPointerException
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at org.projectbuendia.client.ui.lists.LocationListFragment.onViewStateRestored(LocationListFragment.java:66)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:470)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:981)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1929)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at org.projectbuendia.client.ui.BaseLoggedInActivity.onStart(BaseLoggedInActivity.java:144)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.Activity.performStart(Activity.java:5241)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2210)
11-25 16:31:01.235  2580  2580 E AndroidRuntime:    ... 11 more
11-25 16:31:01.235   910  1281 D ActivityManager: New dropbox entry: org.projectbuendia.client.dev, data_app_crash, ea918bfc-fd1c-4a19-92c5-836df086f4f8
11-25 16:31:01.235   910  1281 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.login.LoginActivity
```

**Comment by llvasconcellos** [comment]
@dancunningham The first error seems like an build error. Some library is not been added to the apk package. The last one is strange.
What server did you use in this test? With dev.projectbuendia.org I did not have problems.

**Comment by capnfabs** [comment]
Wow, the first one is complicated.

## Root Cause
- `slf4j` is included by Pebble, but `slf4j` only includes the API by default, and then it's up to consumers to include a logging engine.
- `StaticLoggerBinder` is what `slf4j` uses to resolve the logging engine, so the class isn't included.
- If you don't include an engine, `slf4j` catches the `ClassDefNotFoundError` and explicitly checks for the string `"org/slf4j/impl/StaticLoggerBinder"` somewhere in the error message.
- If it finds the string, it falls back on a no-op logger.
- If it doesn't find this string, it rethrows the exception.

From Dan's bug report, the error message says:

> java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder

Which is different from the string that `slf4j` is looking for (uses dots instead of slashes).

## What's changed?

Dan's tablet is using KitKat (build fingerprint is `Sony/SGP512/SGP512:4.4.4/23.0.1.A.0.167/WP_3Rw:user/release-keys`), and normally everyone is using Lollipop.

From KitKat to Lollipop the default VM changed from Dalvik to ART, which definitely could've changed this behaviour - `ClassDefNotFoundError`s are created by the VM.

I can reproduce this behaviour in an emulator running KitKat.

## Fixes

A couple of options:
- Explicitly include `slf4j-nop` as a dependency for the app, as suggested by the Javadoc on the stub `StaticLoggerBinder` in the slf4j-api package.
- _Require Lollipop_. Not ideal for an Open-source project though, in my opinion.

**Comment by capnfabs** [comment]
Ok so this change broke it, I removed the slf4j library and shouldn't have (apparently: https://github.com/projectbuendia/client/pull/142)

**Comment by llvasconcellos** [comment]
Yes. Now I can reproduce it using the emulator with kitkat.
Fixing it now.
