### ISSUE TITLE
Application is getting error during synchronization from a local server

### ISSUE THREAD

**Issue by viniciusboson** [projectbuendia/client#159]
I'm using the latest changes of dev repository for both client and server. 
When the application tries to synchronize the datas from the local server, it gets the following error:

``` java

11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter: Error during sync
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter: net.sqlcipher.database.SQLiteConstraintException: error code 19: NOT NULL constraint failed: sync_tokens.sync_token
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at net.sqlcipher.database.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1652)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at net.sqlcipher.database.SQLiteDatabase.replaceOrThrow(SQLiteDatabase.java:1572)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.providers.GroupProviderDelegate.insert(GroupProviderDelegate.java:57)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.providers.GroupProviderDelegate.insert(GroupProviderDelegate.java:29)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.providers.DelegatingProvider.insert(DelegatingProvider.java:55)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.providers.BuendiaProvider.insert(BuendiaProvider.java:18)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at android.content.ContentProvider$Transport.insert(ContentProvider.java:239)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at android.content.ContentProviderClient.insert(ContentProviderClient.java:204)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.sync.SyncAdapter.storeSyncToken(SyncAdapter.java:309)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.sync.controllers.PatientsSyncPhaseRunnable.sync(PatientsSyncPhaseRunnable.java:40)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at org.projectbuendia.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:195)
11-29 23:34:01.607 8702-9084/org.projectbuendia.client.dev E/buendia/SyncAdapter:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by viniciusboson** [comment]
Complementing the information:
i’ve reset my local db with `tools/openmrs_setup -f dev` and i’ve removed the application from the tablet to get fully shynchonized ...

**Comment by capnfabs** [comment]
This is working ok for me. My server is at https://github.com/projectbuendia/buendia/commit/40e3272cb403e01c6fc9cba38032c3ee242103b9 and my client is at e6eb06399709b0757979eb102003b416be108cdf. I'm running in an API 22 emulator against a locally-built server.

This field comes directly from the JSON provided by the server. The response from `PatientResource` should always supply a value for this; there are no conditionals that could cause this value to remain unfilled.

Vinicius, would you mind running `git rev-parse HEAD` in both the client and server repos, and putting the output here? I want to verify the versions that you're running against :)

**Comment by capnfabs** [comment]
Vinicius, are you still observing this?

**Comment by viniciusboson** [comment]
Sorry, @capnfabs ... I lost myself  and didn't see your prompt reply... :-/
So, i've tested again, and guest what ?  I can't reproduce it again ..
It's weird because i didn't pull any change .... and that's the same version of yours ...
I've tried to clean the server db running `openmrs_setup -f dev` again ... but it works ..
So, I'm closing this issue ... Thank you ...
