### ISSUE TITLE
Form name lengths overly limited

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#198]
When I try to upload a profile that has a form with a name that's too long, I get the error message below.

I believe this is due to the name being too long as it tries to use a truncated version of the name for the uuid. It would be useful to support longer form names.

```
Error applying profile: nutrition-itfc-102-v3.csv
/usr/bin/buendia-profile-apply:41: Warning: Data truncated for column 'uuid' at row 1
  cursor.execute(query, params)
Traceback (most recent call last):
  File "/usr/bin/buendia-profile-apply", line 501, in <module>
    apply(read_csv(sys.argv[1]))
  File "/usr/bin/buendia-profile-apply", line 497, in apply
    main()
  File "/usr/bin/buendia-profile-apply", line 147, in main
    apply_forms(tabs['form'])
  File "/usr/bin/buendia-profile-apply", line 337, in apply_forms
    put_form(form_rows)
  File "/usr/bin/buendia-profile-apply", line 353, in put_form
    apply_form(rows, form_id)
  File "/usr/bin/buendia-profile-apply", line 381, in apply_form
    section_id = add_field_to_form(form_id, field_id, None, fn)
  File "/usr/bin/buendia-profile-apply", line 185, in add_field_to_form
    required=required and 1 or 0)
  File "/usr/bin/buendia-profile-apply", line 90, in insert
    (table, ', '.join(columns), ', '.join(placeholders)), *values)
  File "/usr/bin/buendia-profile-apply", line 41, in execute
    cursor.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1048, "Column 'form_id' cannot be null")
```

**Comment by dancunningham** [comment]
This is the profile I am attempting to load: https://www.dropbox.com/s/nfhr3lo7kdosguw/nutrition-itfc-102-v3.csv?dl=1
