### ISSUE TITLE
Crashes when form has empty sections

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#199]
**Update:** looks like what is happening is that it doesn't like empty sections, which are caused by a section beginning with a select_multiple.

---

When I am opening the "Initial Physical Exam" form of profile "nutrition-itfc-101.csv" the app crashes as it is loading the form.

This is the profile that was loaded:
https://github.com/projectbuendia/profiles/blob/master/nutrition-itfc-101.csv

Here is a bug report:
https://www.dropbox.com/s/8ay3feu3grezfbs/bugreport-2016-01-14-00-29-13.txt?dl=0

App build 900 (revision #3d9fc283d508b936794e50a3dea0f6004ec96e32).

Connected to dev.projectbuendia.org

Patient ABC/680 "Chinasa Tremblay" in location "UNTI Soins Intensifs".

**Comment by dancunningham** [comment]
Verified that issue occurs still with latest app build (904).

**Comment by dancunningham** [comment]
Same happens with "Surveillance" form in profile "nutrition-itfc-102-v8.csv".

**Comment by capnfabs** [comment]
Infinite recursion?

```
01-14 00:29:02.123  6194  6194 E AndroidRuntime: FATAL EXCEPTION: main
01-14 00:29:02.123  6194  6194 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 6194
01-14 00:29:02.123  6194  6194 E AndroidRuntime: java.lang.StackOverflowError
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.Throwable.<init>(Throwable.java:106)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.Exception.<init>(Exception.java:60)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:51)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:50)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.reflect.Constructor.constructNative(Native Method)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.views.ODKView.addGroupText(ODKView.java:363)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.views.ODKView.<init>(ODKView.java:109)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1445)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
01-14 00:29:02.123  6194  6194 E AndroidRuntime:    at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.
```

**Comment by dancunningham** [comment]
Probably easier to figure out what's going on from the Surveillance form as it's a lot shorter.

**Comment by dancunningham** [comment]
oh, it might be because there is a section name in the form with the same name as a select_multiple field in the form. And I think under the hood it uses sections for select_multiple fields.

**Comment by dancunningham** [comment]
Nope, still crashes.

**Comment by dancunningham** [comment]
Aha! What seemed to be the problem was that having a section starting with a select_multiple means you end up with an empty section, and it doesn't like that.

That really shouldn't cause a crash, it's perfectly reasonable for a user to start a section with a select_multiple.

Well, what I said before might also have been a problem.

**Comment by capnfabs** [comment]
The infinite recursion occurs because `createView` attempts to skip to the next field and call itself again in the event there was a `RuntimeError` processing a field. But, another error occurs when trying to skip to the next field:

```
org.odk.collect.android.exception.JavaRosaException: length=0; index=-1
01-14 00:29:01.303  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at org.odk.collect.android.logic.FormController.stepToNextScreenEvent(FormController.java:716)
```

There are other candidate root problems earlier in the logs:

```
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity: Binary XML file line #4: Error inflating class <unknown>
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity: android.view.InflateException: Binary XML file line #4: Error inflating class <unknown>
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at org.odk.collect.android.views.ODKView.addGroupText(ODKView.java:363)
01-14 00:29:01.983  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at org.odk.collect.android.views.ODKView.<init>(ODKView.java:109)
```

```
01-14 00:29:01.293  6194  6194 E org.odk.collect.android.activities.FormEntryActivity: java.lang.NullPointerException
01-14 00:29:01.293  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at org.odk.collect.android.widgets2.Widget2Factory.create(Widget2Factory.java:52)
01-14 00:29:01.293  6194  6194 E org.odk.collect.android.activities.FormEntryActivity:  at org.odk.collect.android.views.ODKView.<init>(ODKView.java:235)
```

But the root cause could be even earlier - this crash has entirely filled the logs in that bug report.

**Comment by capnfabs** [comment]
The `NullPointerException` appears to be caused by a null question prompt, as returned by `FormController#getQuestionPrompts()`

**Comment by dancunningham** [comment]
Demoting this to a P1 as we can work around it, though it's far from ideal.

**Comment by llvasconcellos** [comment]
I cannot apply any of the profiles because of this error:

``` python
Traceback (most recent call last):
  File "/usr/bin/buendia-profile-apply", line 540, in <module>
    apply(read_csv(sys.argv[1]))
  File "/usr/bin/buendia-profile-apply", line 536, in apply
    main()
  File "/usr/bin/buendia-profile-apply", line 149, in main
    apply_forms(tabs['form'])
  File "/usr/bin/buendia-profile-apply", line 347, in apply_forms
    put_form(form_rows)
  File "/usr/bin/buendia-profile-apply", line 381, in put_form
    apply_form(rows, form_id)
  File "/usr/bin/buendia-profile-apply", line 462, in apply_form
    put_concept(concept_id, label, LOCALE, datatype, obs_class)
  File "/usr/bin/buendia-profile-apply", line 243, in put_concept
    get_datatype_name(new_datatype_id)))
ValueError: Concept 1777000578: cannot change type from Coded to Text
```

What you guys do to solve this problem anyways?

**Comment by llvasconcellos** [comment]
Fixed running this:

``` sql
select concept.concept_id, concept.uuid, datatype.concept_datatype_id, datatype.name, name.name
from concept concept 
join concept_name name on concept.concept_id = name.concept_id
join concept_datatype datatype on concept.datatype_id = datatype.concept_datatype_id
where concept.concept_id in (XXX);

update concept set datatype_id = YYY where concept_id = XXX;
```

**Comment by capnfabs** [comment]
@llvasconcellos I normally just disable the checks in the profile_apply script. @zestyping mentioned once that the reason why they're there is because OpenMRS caches concepts, so if a concept changes while OpenMRS already has it cached, it panics.

@dancunningham FYI, you might see this error on servers that you flash but not on the dev server - every time we set up new local servers we run into this kind of problem.

**Comment by capnfabs** [comment]
Ok, I disabled the recursive "skip to next field if something goes wrong" check, and here's the new stack trace I get:

```
01-22 12:11:16.754 W/System.err(11903): java.lang.NullPointerException: Attempt to invoke virtual method 'int org.javarosa.form.api.FormEntryPrompt.getControlType()' on a null object reference
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.widgets2.Widget2Factory.create(Widget2Factory.java:53)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.views.ODKView.<init>(ODKView.java:236)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1444)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.activities.FormEntryActivity.access$700(FormEntryActivity.java:101)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.activities.FormEntryActivity$QuestionHolderFormVisitor.visit(FormEntryActivity.java:692)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.logic.FormTraverser.traverse(FormTraverser.java:29)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.activities.FormEntryActivity.populateViews(FormEntryActivity.java:573)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.activities.FormEntryActivity.loadingComplete(FormEntryActivity.java:2616)
01-22 12:11:16.754 W/System.err(11903):     at org.odk.collect.android.tasks.FormLoaderTask.onPostExecute(FormLoaderTask.java:535)
01-22 12:11:16.755 W/System.err(11903):     at org.odk.collect.android.tasks.FormLoaderTask.onPostExecute(FormLoaderTask.java:76)
01-22 12:11:16.755 W/System.err(11903):     at android.os.AsyncTask.finish(AsyncTask.java:636)
01-22 12:11:16.755 W/System.err(11903):     at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-22 12:11:16.755 W/System.err(11903):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-22 12:11:16.755 W/System.err(11903):     at android.os.Handler.dispatchMessage(Handler.java:102)
01-22 12:11:16.755 W/System.err(11903):     at android.os.Looper.loop(Looper.java:211)
01-22 12:11:16.755 W/System.err(11903):     at android.app.ActivityThread.main(ActivityThread.java:5373)
01-22 12:11:16.755 W/System.err(11903):     at java.lang.reflect.Method.invoke(Native Method)
01-22 12:11:16.755 W/System.err(11903):     at java.lang.reflect.Method.invoke(Method.java:372)
01-22 12:11:16.755 W/System.err(11903):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
01-22 12:11:16.755 W/System.err(11903):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by capnfabs** [comment]
Here's a summary of the problem(s):
- The ODK code can't handle sections without questions, or nested sections.
- Our `profile_apply` script creates a new section for each `select_multiple`
- ODK can't work out how to skip to the next question after the empty group, so it recurses indefinitely.
