### ISSUE TITLE
"405: Request method DELETE not supported” when voiding an observation

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#223]
This toast message comes up when voiding an observation, even though it seems to work fine in the client and the server.

**Comment by llvasconcellos** [comment]
This message is displayed when the chart rendering is throwing an exception. The chart exception is captured by the toast message and an misguided error is displayed.
To solve this problem we need to make sure only real network error are displayed.

**Comment by llvasconcellos** [comment]
The exception:

``` java
01-19 13:27:22.697  25779-25779/org.projectbuendia.client.dev E/buendia/PebbleExtension﹕ Could not apply format {1,abbr}
    java.lang.StringIndexOutOfBoundsException: length=2; regionStart=0; regionLength=3
            at java.lang.String.startEndAndLength(String.java:504)
            at java.lang.String.substring(String.java:1333)
            at org.projectbuendia.client.ui.chart.ObsFormat$ObsAbbrFormat.formatObsValue(ObsFormat.java:240)
            at org.projectbuendia.client.ui.chart.ObsFormat$ObsOutputFormat.format(ObsFormat.java:188)
            at java.text.MessageFormat.formatImpl(MessageFormat.java:589)
            at java.text.MessageFormat.format(MessageFormat.java:550)
            at java.text.MessageFormat.format(MessageFormat.java:702)
            at org.projectbuendia.client.ui.chart.ObsFormat.format(ObsFormat.java:136)
            at java.text.Format.format(Format.java:93)
            at org.projectbuendia.client.ui.chart.PebbleExtension.formatValues(PebbleExtension.java:221)
            at org.projectbuendia.client.ui.chart.PebbleExtension$FormatValueFilter.apply(PebbleExtension.java:167)
            at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:54)
            at com.mitchellbosecke.pebble.node.SetNode.render(SetNode.java:33)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:56)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:50)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:97)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:97)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:32)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.buildContent(PebbleTemplateImpl.java:61)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:107)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:82)
            at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.renderTemplate(ChartRenderer.java:293)
            at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.getHtml(ChartRenderer.java:260)
            at org.projectbuendia.client.ui.chart.ChartRenderer.render(ChartRenderer.java:104)
            at org.projectbuendia.client.ui.chart.PatientChartActivity$Ui.updateTilesAndGrid(PatientChartActivity.java:446)
            at org.projectbuendia.client.ui.chart.PatientChartController.updatePatientObsUi(PatientChartController.java:553)
            at org.projectbuendia.client.ui.chart.PatientChartController$EventSubscriber.onEventMainThread(PatientChartController.java:784)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
            at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
            at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
            at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
            at de.greenrobot.event.EventBus.post(EventBus.java:263)
            at org.projectbuendia.client.ui.dialogs.VoidObservationsDialogFragment$1.onClick(VoidObservationsDialogFragment.java:116)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5373)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
01-19 13:27:22.733  25779-25833/org.projectbuendia.client.dev E/Volley﹕ [32287] BasicNetwork.performRequest: Unexpected response code 405 for http://192.168.0.9:9000/openmrs/ws/rest/v1/projectbuendiahttp://192.168.0.9:9000/openmrs/ws/rest/v1/obs/8bd9a5dd-f39e-4c2f-be77-6ee0ecab485a
01-19 13:27:22.738  25779-25779/org.projectbuendia.client.dev E/buendia/PebbleExtension﹕ Could not apply format {1,abbr}
    java.lang.StringIndexOutOfBoundsException: length=2; regionStart=0; regionLength=3
            at java.lang.String.startEndAndLength(String.java:504)
            at java.lang.String.substring(String.java:1333)
            at org.projectbuendia.client.ui.chart.ObsFormat$ObsAbbrFormat.formatObsValue(ObsFormat.java:240)
            at org.projectbuendia.client.ui.chart.ObsFormat$ObsOutputFormat.format(ObsFormat.java:188)
            at java.text.MessageFormat.formatImpl(MessageFormat.java:589)
            at java.text.MessageFormat.format(MessageFormat.java:550)
            at java.text.MessageFormat.format(MessageFormat.java:702)
            at org.projectbuendia.client.ui.chart.ObsFormat.format(ObsFormat.java:136)
            at java.text.Format.format(Format.java:93)
            at org.projectbuendia.client.ui.chart.PebbleExtension.formatValues(PebbleExtension.java:221)
            at org.projectbuendia.client.ui.chart.PebbleExtension$FormatValueFilter.apply(PebbleExtension.java:167)
            at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:54)
            at com.mitchellbosecke.pebble.node.SetNode.render(SetNode.java:33)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:56)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:50)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:97)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:97)
            at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
            at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:32)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.buildContent(PebbleTemplateImpl.java:61)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:107)
            at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:82)
            at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.renderTemplate(ChartRenderer.java:293)
            at org.projectbuendia.client.ui.chart.ChartRenderer$GridHtmlGenerator.getHtml(ChartRenderer.java:260)
            at org.projectbuendia.client.ui.chart.ChartRenderer.render(ChartRenderer.java:104)
            at org.projectbuendia.client.ui.chart.PatientChartActivity$Ui.updateTilesAndGrid(PatientChartActivity.java:446)
            at org.projectbuendia.client.ui.chart.PatientChartController.updatePatientObsUi(PatientChartController.java:553)
            at org.projectbuendia.client.ui.chart.PatientChartController$EventSubscriber.onEventMainThread(PatientChartController.java:784)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
            at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
            at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
            at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
            at de.greenrobot.event.EventBus.post(EventBus.java:263)
            at org.projectbuendia.client.ui.dialogs.VoidObservationsDialogFragment$1.onClick(VoidObservationsDialogFragment.java:116)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5373)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```
