### ISSUE TITLE
Can't save any form.

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#227]
Impossible to save any form.

``` java
01-19 12:45:44.996  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ Error submitting form to server
    com.android.volley.ServerError
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:161)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)
01-19 12:45:44.997  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ {"error":{"message":"Unable to convert object into response content","code":"org.openmrs.projectbuendia.webservices.rest.XformInstanceResource:134","detail":"org.openmrs.module.webservices.rest.web.response.ConversionException: Error processing xform data\n\tat org.openmrs.projectbuendia.webservices.rest.XformInstanceResource.createInner(XformInstanceResource.java:134)\n\tat org.openmrs.projectbuendia.webservices.rest.XformInstanceResource.create(XformInstanceResource.java:112)\n\tat org.openmrs.module.webservices.rest.web.v1_0.controller.MainResourceController.create(MainResourceController.java:86)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:755)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1506)\n\tat org.openmrs.module.web.filter.ForcePasswordChangeFilter.doFilter(ForcePasswordChangeFilter.java:61)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:72)\n\tat org.openmrs.module.xforms.web.XformsFilter.doFilter(XformsFilter.java:69)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.web.filter.GZIPFilter.doFilterInternal(GZIPFilter.java:64)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.webservices.rest.web.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:108)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:58)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.web.filter.ModuleFilter.doFilter(ModuleFilter.java:54)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.web.filter.OpenmrsFilter.doFilterInternal(OpenmrsFilter.java:107)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:105)
01-19 12:45:44.997  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ Server error. Internal error stack trace:
```

**Comment by llvasconcellos** [comment]
@capnfabs Just to remind you:
https://github.com/projectbuendia/client/pull/220#issuecomment-172882805

**Comment by capnfabs** [comment]
Sorry! This one's super bad, it's my first priority today.

**Comment by capnfabs** [comment]
Leonardo, I can't reproduce this. Can you check that you're running latest Android client and against latest server?

I made changes to `XformsInstanceResource` in a recent server PR, so if your local server isn't up to date, it will break.

**Comment by capnfabs** [comment]
Can't reproduce with latest dev client against dev server either.

**Comment by llvasconcellos** [comment]
@capnfabs Sorry for making you waste time. I was running an outdated server. It's working now!

**Comment by capnfabs** [comment]
No worries :)
