### ISSUE TITLE
Can't select a patient

### ISSUE THREAD

**Issue by viniciusboson** [projectbuendia/client#230]
Working on branch [PR#172](https://github.com/projectbuendia/client/pull/172), after merging from buendia repository, both client and server, it started throwing an exception when i try to select an patient:

``` java
01-21 07:42:36.057 18363-18363/org.projectbuendia.client.dev E/SysUtils: ApplicationContext is null in ApplicationStatus
01-21 07:42:36.208 18363-18363/org.projectbuendia.client.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: org.projectbuendia.client.dev, PID: 18363
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{org.projectbuendia.client.dev/org.projectbuendia.client.ui.chart.PatientChartActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.projectbuendia.client.models.Chart.rowGroups' on a null object reference
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:211)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                                Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.projectbuendia.client.models.Chart.rowGroups' on a null object reference
                                                                                   at org.projectbuendia.client.sync.ChartDataHelper.getCharts(ChartDataHelper.java:323)
                                                                                   at org.projectbuendia.client.ui.chart.PatientChartController.<init>(PatientChartController.java:229)
                                                                                   at org.projectbuendia.client.ui.chart.PatientChartActivity.onCreateImpl(PatientChartActivity.java:257)
                                                                                   at org.projectbuendia.client.ui.BaseLoggedInActivity.onCreate(BaseLoggedInActivity.java:80)
                                                                                   at android.app.Activity.performCreate(Activity.java:5990)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:156) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:211) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5373) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
```

I'm using my [server repository](https://github.com/viniciusboson/buendia), which is updated with buendia's.
When i try to use [buendia's server[(dev.projectbuendia.org), this error doesn't appear.

**Comment by capnfabs** [comment]
Hey @viniciusboson, I think this is as a result of a change @llvasconcellos made recently. I can't remember which change it was now (maybe Leonardo knows?) but you need to re-apply the profile you had set up and then this should work fine :)

**Comment by capnfabs** [comment]
Please try that, and close the bug if that fixes it.

**Comment by llvasconcellos** [comment]
Hi @viniciusboson . This is related to multiple charts. Can you re-apply your profile again?
This should solve it.
I'm closing this one, please open it again if the problem persists.

**Comment by viniciusboson** [comment]
I've re-applied my profile and the error persists.
What am i missing, @llvasconcellos  ?

**Comment by llvasconcellos** [comment]
@viniciusboson did you clear the tablet data and did a full resync?
When you apply a new profile it takes a while to the chart definitions sync.
And, to be really sure, you could do a full renew of your installation:
run on the server:

``` sh
git checkout dev
git pull
tools/openmrs_setup -f dev
tools/openmrs_build
tools/openmrs_run
```

Then apply a new profile on OpenMRS.
Uninstall the client app, update your dev branch, build a new app and run.
If after all that you still experience this problem come back here!

**Comment by viniciusboson** [comment]
After reset the entire environment, it worked. Thx @llvasconcellos !!!
