### ISSUE TITLE
Crash in patient list activity

### ISSUE THREAD

**Issue by zestyping** [projectbuendia/client#298]
To be investigated.

```
06-17 17:37:53.861  6467  6467 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.ui.PatientListTypedCursorAdapter.getGroup(PatientListTypedCursorAdapter.java:120)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.ui.PatientListTypedCursorAdapter.getChildrenCount(PatientListTypedCursorAdapter.java:124)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.widget.ExpandableListConnector.refreshExpGroupMetadataList(ExpandableListConnector.java:563)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.widget.ExpandableListConnector.expandGroup(ExpandableListConnector.java:688)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.widget.ExpandableListView.expandGroup(ExpandableListView.java:750)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.widget.ExpandableListView.expandGroup(ExpandableListView.java:734)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.widgets.GroupedListView.expandAllGroups(GroupedListView.java:70)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.widgets.GroupedListView.access$000(GroupedListView.java:31)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.widgets.GroupedListView$2.onChanged(GroupedListView.java:63)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.widget.BaseExpandableListAdapter.notifyDataSetChanged(BaseExpandableListAdapter.java:56)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.ui.PatientListTypedCursorAdapter$FetchObservationsTask.onPostExecute(PatientListTypedCursorAdapter.java:259)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at org.projectbuendia.client.ui.PatientListTypedCursorAdapter$FetchObservationsTask.onPostExecute(PatientListTypedCursorAdapter.java:251)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7002)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
06-17 17:37:53.861  6467  6467 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by mjanes** [comment]
@zestyping Do you have any known steps to replicate this?

Can put a bandaid on and check nullity of mLocations in PatientLitTypedCursorAdapter.getGroup, but that doesn't explain why mLocations is null.

With the logs there, it looks like as though FetchObservationsTask.onPostExecute's call to notifyDatasetChanged is triggering this, but mLocations in initialized a few lines before the only place that FetchObesrvationsTask is executed.

Am concerned about having a non-static inner async task referencing back to call notify dataset changed, but that will take some more substantive changes.

**Comment by zestyping** [comment]
You're right, we do need a specific set of steps to replicate this.  I've seen it happen in a few different situations; the last time was upon waking the tablet from sleep.  But it would help a lot to narrow it down!

**Comment by zestyping** [comment]
This is a duplicate of #352.
