### ISSUE TITLE
Client App not working

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#3]
After this commit: https://github.com/projectbuendia/client/commit/ea7ed1d444e2b76458202a1abbbff945325b16aa the client application does not work correctly.
1. The openmrsRootUrlDefault value is set to openmrsRootUrlFantastica and not the default openmrsRootUrlDev as described in the documentation.

``` Gradle
def openmrsRootUrlDefault = openmrsRootUrlFantastica;
```

setting openmrsRootUrlDefault to openmrsRootUrlDev improves the app connection to the server.

``` Gradle
def openmrsRootUrlDefault = openmrsRootUrlDev;
```
1. The new def added requireWifi is causing some problems.

``` Gradle
def requireWifi = "true"
```

Setting it to false seems to correct the problems:

``` Gradle
def requireWifi = "false"
```
## Here are some screenshots with requireWifi = "true"

*The list of users appear in the screen with the right server address in (openmrsRootUrlDefault):

![screenshot from 2015-08-29 15 17 52](https://cloud.githubusercontent.com/assets/1710823/9563735/608b35ae-4e64-11e5-988f-e4015583cd84.png)

_Selecting one user gives the following error:_

![screenshot from 2015-08-29 15 18 28](https://cloud.githubusercontent.com/assets/1710823/9563737/608dbcf2-4e64-11e5-93b6-b6a4c8751d56.png)

_Selecting "settings" force quit the app:_

![screenshot from 2015-08-29 15 18 37](https://cloud.githubusercontent.com/assets/1710823/9563736/608d1658-4e64-11e5-9740-650179606236.png)
## The logcat:

``` text
08-29 15:20:48.764    6861-6861/? I/art﹕ Not late-enabling -Xcheck:jni (already on)
08-29 15:20:48.764    6861-6861/? I/art﹕ Late-enabling JIT
08-29 15:20:48.780    6861-6861/? I/art﹕ JIT created with code_cache_capacity=2MB compile_threshold=1000
08-29 15:20:48.867    6861-6861/org.projectbuendia.client.dev I/PropertyManager﹕ calling constructor
08-29 15:20:48.892    6861-6861/org.projectbuendia.client.dev W/linker﹕ /data/app/org.projectbuendia.client.dev-2/lib/x86/libsqlcipher_android.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
08-29 15:20:48.895    6861-6861/org.projectbuendia.client.dev I/Database﹕ JNI_OnLoad called
08-29 15:20:48.895    6861-6861/org.projectbuendia.client.dev I/Database﹕ JNI_OnLoad register methods
08-29 15:20:48.988    6861-6861/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class org.projectbuendia.client.events.diagnostics.TroubleshootingActionsChangedEvent
08-29 15:20:48.988    6861-6861/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
08-29 15:20:49.238    6861-6861/org.projectbuendia.client.dev I/buendia/OpenMrsServer﹕ Logging to server: [time=1440872449238, event=resumed_activity, class=LoginActivity]
08-29 15:20:49.240    6861-6861/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://dev.projectbuendia.org:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440872449238;event=resumed_activity;class=LoginActivity
08-29 15:20:49.245    6861-6887/org.projectbuendia.client.dev D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-29 15:20:49.249    6861-6861/org.projectbuendia.client.dev D/﹕ HostConnection::get() New Host Connection established 0xa17f1870, tid 6861
08-29 15:20:49.265    6861-6888/org.projectbuendia.client.dev I/buendia/UserStore﹕ Retrieving users from db
08-29 15:20:49.302    6861-6887/org.projectbuendia.client.dev D/﹕ HostConnection::get() New Host Connection established 0xa1063090, tid 6887
08-29 15:20:49.312    6861-6887/org.projectbuendia.client.dev I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-29 15:20:49.344    6861-6887/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 15:20:49.344    6861-6887/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa10bdce0, error=EGL_SUCCESS
08-29 15:20:49.500    6861-6888/org.projectbuendia.client.dev I/buendia/UserStore﹕ Found 9 users in db
08-29 15:20:49.512    6861-6884/org.projectbuendia.client.dev D/buendia/UpdateServerHealthCheck﹕ Update server check completed, OK.
08-29 15:20:49.513    6861-6861/org.projectbuendia.client.dev D/buendia/LoginController﹕ Loaded list of 9 users

```

**Comment by zestyping** [comment]
Hi, ea7ed1d is a bit out of date; there have been 10 revisions committed since then.  Try the most recent one, http://builds.projectbuendia.org/client-dev/buendia-client-dev-0.0.724.apk — it doesn't have these problems for me.

Closing for now.  Please re-open if you still see problems.  Thanks!

**Comment by llvasconcellos** [comment]
I cloned the repo yesterday, but ok. It's outdated. I'll update my repo and build it again.

**Comment by llvasconcellos** [comment]
I updated my repo and there are still problems:
1. http://192.168.1.161:9000/openmrs is still the default url to OpenMRS instead of http://dev.projectbuendia.org:9000/openmrs which differs from docs. There are new devs starting on the project and this could be a distraction. At least the docs should be updated.
2. Now the setup screen opens (no more force quit) but the url value is not saved. Did not tested other fields.

I haven't tested your apk, just synced my repository with buendia dev branch.

Here is the logcat:

``` text
08-29 23:05:55.123    7974-7974/? I/art﹕ Not late-enabling -Xcheck:jni (already on)
08-29 23:05:55.123    7974-7974/? I/art﹕ Late-enabling JIT
08-29 23:05:55.125    7974-7974/? I/art﹕ JIT created with code_cache_capacity=2MB compile_threshold=1000
08-29 23:05:55.343    7974-7974/org.projectbuendia.client.dev I/PropertyManager﹕ calling constructor
08-29 23:05:55.449    7974-7974/org.projectbuendia.client.dev W/linker﹕ /data/app/org.projectbuendia.client.dev-1/lib/x86/libsqlcipher_android.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
08-29 23:05:55.471    7974-7974/org.projectbuendia.client.dev I/Database﹕ JNI_OnLoad called
08-29 23:05:55.471    7974-7974/org.projectbuendia.client.dev I/Database﹕ JNI_OnLoad register methods
08-29 23:05:55.575    7974-7974/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class org.projectbuendia.client.events.diagnostics.TroubleshootingActionsChangedEvent
08-29 23:05:55.575    7974-7974/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
08-29 23:05:55.877    7974-7974/org.projectbuendia.client.dev I/buendia/OpenMrsServer﹕ Logging to server: [time=1440900355877, event=resumed_activity, class=LoginActivity]
08-29 23:05:55.879    7974-7974/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900355877;event=resumed_activity;class=LoginActivity
08-29 23:05:55.883    7974-8011/org.projectbuendia.client.dev D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-29 23:05:55.886    7974-7974/org.projectbuendia.client.dev D/﹕ HostConnection::get() New Host Connection established 0xa4138990, tid 7974
08-29 23:05:55.920    7974-8011/org.projectbuendia.client.dev D/﹕ HostConnection::get() New Host Connection established 0xa4138ae0, tid 8011
08-29 23:05:55.926    7974-8011/org.projectbuendia.client.dev I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-29 23:05:55.940    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:05:55.940    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xad7131a0, error=EGL_SUCCESS
08-29 23:05:55.957    7974-8012/org.projectbuendia.client.dev I/buendia/UserStore﹕ Retrieving users from db
08-29 23:05:56.134    7974-8005/org.projectbuendia.client.dev D/buendia/UpdateServerHealthCheck﹕ Update server check completed, OK.
08-29 23:05:56.193    7974-8012/org.projectbuendia.client.dev I/buendia/UserStore﹕ No users found in db -- refreshing
08-29 23:05:56.193    7974-8012/org.projectbuendia.client.dev I/buendia/UserStore﹕ Getting user list from server
08-29 23:05:56.239    7974-8012/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/user?q=
08-29 23:06:04.530    7974-7974/org.projectbuendia.client.dev I/buendia/OpenMrsServer﹕ Logging to server: [time=1440900364529, event=settings_button_pressed]
08-29 23:06:04.539    7974-7974/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900364529;event=settings_button_pressed
08-29 23:06:04.683    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:06:04.683    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa0c69260, error=EGL_SUCCESS
08-29 23:06:04.863    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79f0f0
08-29 23:06:07.571    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:06:07.571    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa193f200, error=EGL_SUCCESS
08-29 23:06:10.969    7974-7974/org.projectbuendia.client.dev D/Volley﹕ [1] Request.finish: 15089 ms: [ ] http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900355877;event=resumed_activity;class=LoginActivity 0x85bc0e90 NORMAL 1
08-29 23:06:15.112    7974-8004/org.projectbuendia.client.dev W/buendia/BuendiaApiHealthCheck﹕ Could not perform OpenMRS health check using URL 'http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/a3657203-cfed-44b8-8e3f-960f8d4cf3b3'.
08-29 23:06:15.112    7974-8004/org.projectbuendia.client.dev W/MessageQueue﹕ Handler (android.os.Handler) {9c9cdfe} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {9c9cdfe} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
            at android.os.Handler.enqueueMessage(Handler.java:631)
            at android.os.Handler.sendMessageAtTime(Handler.java:600)
            at android.os.Handler.sendMessageDelayed(Handler.java:570)
            at android.os.Handler.postDelayed(Handler.java:398)
            at org.projectbuendia.client.diagnostics.BuendiaApiHealthCheck$BuendiaModuleHealthCheckRunnable.run(BuendiaApiHealthCheck.java:189)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
08-29 23:06:19.718    7974-7974/org.projectbuendia.client.dev D/Volley﹕ [1] Request.finish: 15179 ms: [ ] http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900364529;event=settings_button_pressed 0x85bc0e90 NORMAL 3
08-29 23:06:43.465    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79f0f0
08-29 23:06:52.395    7974-7985/org.projectbuendia.client.dev E/Database﹕ close() was never explicitly called on database '/data/user/0/org.projectbuendia.client.dev/databases/buendia.db'
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
            at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1945)
            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
            at org.projectbuendia.client.sync.Database.getWritableDatabase(Database.java:186)
            at org.projectbuendia.client.sync.Database.clear(Database.java:174)
            at org.projectbuendia.client.widget.EditAndClearDataPreference.onDialogClosed(EditAndClearDataPreference.java:34)
            at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
            at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1323)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-29 23:07:07.823    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:07.823    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa047baa0, error=EGL_SUCCESS
08-29 23:07:15.020    7974-7974/org.projectbuendia.client.dev D/Volley﹕ [1] Request.finish: 78780 ms: [ ] http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/user?q= 0x85bc0e90 NORMAL 2
08-29 23:07:15.021    7974-8012/org.projectbuendia.client.dev E/buendia/UserManager﹕ Load users task failed
    java.util.concurrent.ExecutionException: com.android.volley.VolleyError: java.net.ConnectException: failed to connect to /192.168.1.161 (port 9000) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
            at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:88)
            at org.projectbuendia.client.user.UserStore.syncKnownUsers(UserStore.java:105)
            at org.projectbuendia.client.user.UserStore.loadKnownUsers(UserStore.java:70)
            at org.projectbuendia.client.user.UserManager$LoadKnownUsersTask.doInBackground(UserManager.java:275)
            at org.projectbuendia.client.user.UserManager$LoadKnownUsersTask.doInBackground(UserManager.java:266)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: com.android.volley.VolleyError: java.net.ConnectException: failed to connect to /192.168.1.161 (port 9000) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at org.projectbuendia.client.net.OpenMrsServer$1.onErrorResponse(OpenMrsServer.java:110)
            at com.android.volley.Request.deliverError(Request.java:587)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: com.android.volley.NoConnectionError: java.net.ConnectException: failed to connect to /192.168.1.161 (port 9000) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:140)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)
     Caused by: java.net.ConnectException: failed to connect to /192.168.1.161 (port 9000) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:234)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
            at java.net.Socket.connect(Socket.java:884)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
            at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
            at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
            at com.android.okhttp.Connection.connect(Connection.java:152)
            at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
            at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
            at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
            at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:109)
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:93)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)
     Caused by: android.system
08-29 23:07:15.021    7974-8012/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class org.projectbuendia.client.events.user.KnownUsersLoadFailedEvent
08-29 23:07:15.021    7974-8012/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
08-29 23:07:15.023    7974-7974/org.projectbuendia.client.dev E/buendia/UserManager﹕ No users returned from db
08-29 23:07:15.023    7974-7974/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class org.projectbuendia.client.events.user.KnownUsersLoadFailedEvent
08-29 23:07:15.023    7974-7974/org.projectbuendia.client.dev D/Event﹕ No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
08-29 23:07:19.195    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79f0f0
08-29 23:07:20.346    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:20.346    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa04bfe20, error=EGL_SUCCESS
08-29 23:07:21.893    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:21.893    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa162eac0, error=EGL_SUCCESS
08-29 23:07:23.092    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xa18fbc50
08-29 23:07:23.411    7974-7974/org.projectbuendia.client.dev E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-29 23:07:23.411    7974-7974/org.projectbuendia.client.dev E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-29 23:07:23.462    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:23.462    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa162eb80, error=EGL_SUCCESS
08-29 23:07:23.714    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xa18fcac0
08-29 23:07:23.717    7974-7974/org.projectbuendia.client.dev W/InputEventReceiver﹕ Attempted to finish an input event but the input event receiver has already been disposed.
08-29 23:07:23.802    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:23.802    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa0c69140, error=EGL_SUCCESS
08-29 23:07:24.579    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xa18fcac0
08-29 23:07:24.652    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:24.652    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa0c69fa0, error=EGL_SUCCESS
08-29 23:07:25.666    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xa18fbbe0
08-29 23:07:31.189    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79f0f0
08-29 23:07:33.669    7974-7974/org.projectbuendia.client.dev I/Database﹕ sqlite returned: error code = 17, msg = statement aborts at 12: [SELECT full_sync_start_time, full_sync_end_time, obs_sync_time FROM misc WHERE 1 and (_id=?)] database schema has changed
08-29 23:07:33.670    7974-7974/org.projectbuendia.client.dev D/buendia/AppModel﹕ Sync timing result count: 0
08-29 23:07:33.730    7974-7974/org.projectbuendia.client.dev I/buendia/OpenMrsServer﹕ Logging to server: [time=1440900453730, event=resumed_activity, class=LoginActivity]
08-29 23:07:33.733    7974-7974/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900453730;event=resumed_activity;class=LoginActivity
08-29 23:07:33.771    7974-7983/org.projectbuendia.client.dev W/art﹕ Suspending all threads took: 16.447ms
08-29 23:07:33.810    7974-8011/org.projectbuendia.client.dev W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-29 23:07:33.810    7974-8011/org.projectbuendia.client.dev W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa162fe40, error=EGL_SUCCESS
08-29 23:07:33.846    7974-8610/org.projectbuendia.client.dev I/buendia/UserStore﹕ Retrieving users from db
08-29 23:07:33.863    7974-8610/org.projectbuendia.client.dev I/Database﹕ sqlite returned: error code = 17, msg = statement aborts at 27: [SELECT * FROM users WHERE 1 ORDER BY full_name] database schema has changed
08-29 23:07:33.863    7974-8610/org.projectbuendia.client.dev I/buendia/UserStore﹕ No users found in db -- refreshing
08-29 23:07:33.863    7974-8610/org.projectbuendia.client.dev I/buendia/UserStore﹕ Getting user list from server
08-29 23:07:33.864    7974-8610/org.projectbuendia.client.dev I/buendia/VolleySingleton﹕ queueing request: 0 http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/user?q=
08-29 23:07:33.923    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79a8c0
08-29 23:07:34.295    7974-8753/org.projectbuendia.client.dev D/buendia/UpdateServerHealthCheck﹕ Update server check completed, OK.
08-29 23:07:38.667    7974-8011/org.projectbuendia.client.dev E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab79f0f0
08-29 23:07:43.686    7974-7985/org.projectbuendia.client.dev E/Database﹕ close() was never explicitly called on database '/data/user/0/org.projectbuendia.client.dev/databases/buendia.db'
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
            at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1945)
            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
            at org.projectbuendia.client.sync.Database.getWritableDatabase(Database.java:186)
            at org.projectbuendia.client.sync.Database.clear(Database.java:174)
            at org.projectbuendia.client.widget.EditAndClearDataPreference.onDialogClosed(EditAndClearDataPreference.java:34)
            at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
            at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1323)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-29 23:07:48.870    7974-7974/org.projectbuendia.client.dev D/Volley﹕ [1] Request.finish: 15136 ms: [ ] http://192.168.1.161:9000/openmrs/ws/rest/v1/projectbuendia/concept/5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;time=1440900453730;event=resumed_activity;class=LoginActivity 0x85bc0e90 NORMAL 4
```

**Comment by zestyping** [comment]
Sorry about that!  I had some local changes that I hadn't committed and pushed.  These things should be fixed now.  I've also given the settings a bit of a cleanup so that you only need to specify the hostname, and the default is dev.projectbuendia.org as it should be.  Could you give the latest build a try, and let me know how that goes?

(For convenience, you can always get the latest apk from http://builds.projectbuendia.org/ .)

**Comment by llvasconcellos** [comment]
Tested and it's working fine. Thanks.
