### ISSUE TITLE
Cannot create new patients

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#308]
Somehow I got into a state where I can not create new patients while testing validation on the Add New Patient Form. 

**Steps**: 
1. Log on via my recently created profile - Sarawr Rawr
2. Click Add new patient on any screen
3. Enter valid data for everything. 
4. Click OK
Result: App stops. (Patient is created when I open app again). 
Expected: App will not stop when patient is created. 

**Log**: 
via @zestyping 

```
2019-06-19 12:40:27.001 ? E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
    Process: org.projectbuendia.client.dev, PID: 27272
    java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
        at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:925)
        at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
        at android.database.sqlite.SQLiteSession.executeSpecial(SQLiteSession.java:894)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:613)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
        at org.projectbuendia.client.providers.SQLiteDatabaseTransactionHelper.rollbackNamedTransaction(SQLiteDatabaseTransactionHelper.java:45)
        at org.projectbuendia.client.sync.SyncAdapter.rollbackSavepoint(SyncAdapter.java:277)
        at org.projectbuendia.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:204)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:321)
```

**Comment by saratheneale** [comment]
Closing this in favor of #319
