### ISSUE TITLE
Add New Patient -> Crashes

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#310]
Form Fields: 
id, given name, family name, sex, years + months, 

Not including Months Input crashes the app. 
Not including gender crashes the app. 
Not including a Family name crashes the app. 
Not including a Given name crashes the app. 
Once a patient without a name is on the server, adding new patients keeps crashing it. 

Things to consider: 
- What fields are required? 
- What happens if each field is blank? 
- What happens if year is not filled out, but months is? Ex: 40 months. or 11 months
- What if months is greater than 11? 
- What is someone inputs 6 years, 13 months?
- What are character limits for each field? (i.e. name: 50)

**Comment by saratheneale** [comment]
Here's a log when I add a Patient with No Sex. 
This is a similar error to #319 . I don't think its useful to get further crash logs on this until #319 is fixed. 


Adding a Patient with No Sex: 

```
06-21 11:45:01.104 31062 31391 E AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
06-21 11:45:01.104 31062 31391 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 31062
06-21 11:45:01.104 31062 31391 E AndroidRuntime: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:925)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeSpecial(SQLiteSession.java:894)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:613)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at org.projectbuendia.client.providers.SQLiteDatabaseTransactionHelper.rollbackNamedTransaction(SQLiteDatabaseTransactionHelper.java:45)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at org.projectbuendia.client.sync.SyncAdapter.rollbackSavepoint(SyncAdapter.java:277)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at org.projectbuendia.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:204)
06-21 11:45:01.104 31062 31391 E AndroidRuntime: 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:321)
06-21 11:45:01.107  2913  6281 D Debug   : !@DumpState : SHIP
06-21 11:45:01.108  2913  6281 D Debug   : !@DumpState : debug level:0x4f4c
06-21 11:45:01.108  2913  6281 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
06-21 11:45:01.108  2913  6281 W ActivityManager: crash : org.projectbuendia.client.dev,0
06-21 11:45:01.110  2913  6281 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.chart.PatientChartActivity
06-21 11:45:01.116  2913  6281 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.lists.FilteredPatientListActivity
06-21 11:45:01.118 31062 31062 W buendia/BaseLoggedInAct: The user has switched. I don't know how to deal with that right now
06-21 11:45:01.123 20872 20872 I DMT-SMReceiver: Received : com.samsung.android.sm.ACTION_ERROR
06-21 11:45:01.124 20872 20872 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1545 android.content.ContextWrapper.startService:669 android.content.ContextWrapper.startService:669 com.samsung.android.sm.common.SmartManagerReceiver.a:240 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:119 
06-21 11:45:01.126  2913  2929 I ActivityManager: Showing crash dialog for package org.projectbuendia.client.dev u0
```

**Comment by saratheneale** [comment]
These crashes were related to #319. These crashes were not related to fields blank.
Verified each blank case works in `fixed-319.apx`

**Comment by zestyping** [comment]
@saratheneale Oh don't close this just yet—the fix is in a feature branch but it hasn't been merged into `dev` yet.  I'll attach this issue to the pull request so that it closes when the pull request is closed.
