### ISSUE TITLE
Cannot add new patients if a patient with no name is on the server - App Crashes

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#319]
1. Add a patient with no Given name or no Family Name. 
2. The app crashes. Select open app again. See #310
3. Add a patient with perfect valid data
Result: app crashes. 
Expected: No crash! 

Now I need to reset the server in order to be able to add patients with no crash. 

Log attached: 
[foo.txt](https://github.com/projectbuendia/client/files/3311476/foo.txt)

Same issue #308 also has a log attached.

**Comment by saratheneale** [comment]
I fixed all patient names on the server and it still crashes when I add new patients.

**Comment by zestyping** [comment]
Here's the exception dump:

```06-16 11:14:58.126 23502 23594 E AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-2
06-16 11:14:58.126 23502 23594 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 23502
06-16 11:14:58.126 23502 23594 E AndroidRuntime: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:925)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeSpecial(SQLiteSession.java:894)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:613)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at org.projectbuendia.client.providers.SQLiteDatabaseTransactionHelper.rollbackNamedTransaction(SQLiteDatabaseTransactionHelper.java:45)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at org.projectbuendia.client.sync.SyncAdapter.rollbackSavepoint(SyncAdapter.java:277)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at org.projectbuendia.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:204)
06-16 11:14:58.126 23502 23594 E AndroidRuntime: 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:321)
06-16 11:14:58.130  2747  5644 D Debug   : !@DumpState : SHIP
06-16 11:14:58.130  2747  5644 D Debug   : !@DumpState : debug level:0x4f4c
06-16 11:14:58.130  2747  5644 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
06-16 11:14:58.130  2747  5644 W ActivityManager: crash : org.projectbuendia.client.dev,0
06-16 11:14:58.133  2747  5644 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.chart.PatientChartActivity
06-16 11:14:58.138  2747  5644 W ActivityManager:   Force finishing activity org.projectbuendia.client.dev/org.projectbuendia.client.ui.lists.LocationListActivity
06-16 11:14:58.145  2747  2764 I ActivityManager: Showing crash dialog for package org.projectbuendia.client.dev u0
```

**Comment by saratheneale** [comment]
Verified fixed in `fix-319.apk` 🎉

**Comment by zestyping** [comment]
This fix isn't on `dev` yet—reopening for now.  It'll close when the PR is merged.
