### ISSUE TITLE
Submitting form fails with "Index 0 requested" error

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#329]
Sometimes forms will not save despite having valid data. 
I have seen this on the New Round Form and the Ebola Lab Test Form. 

In the case with the Ebola Lab Test form, often I forget to Confirm Result button and get an expected error. Then clicking the button and submit again. I see the following error. 

`Sorry, form save failed: Index 0 requested, with a size of 0`

![Screenshot_20190620-195357_Buendia](https://user-images.githubusercontent.com/3619338/60051826-b7824f80-9688-11e9-8884-9844f24e1628.jpg)

**Comment by saratheneale** [comment]
Relevant log:
This all took place around 14:10PST / 21:10UTC on June 24, 2019. 
Note the `Index 0 requested, with a size of 0` 

[329.txt](https://github.com/projectbuendia/client/files/3322611/329.txt)

**Comment by zestyping** [comment]
All the stack traces we have managed to collect for this error look the same:

```
07-11 12:08:59.688 14619 16144 I SaveToDiskTask: No instance found, creating
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: Index 0 requested, with a size of 0
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:468)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.updateInstanceDatabase(SaveToDiskTask.java:198)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.exportData(SaveToDiskTask.java:263)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:125)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:49)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-11 12:08:59.698 14619 16144 E SaveToDiskTask: 	at java.lang.Thread.run(Thread.java:764)
07-11 12:08:59.743 14619 14619 W org.odk.collect.android.activities.FormEntryActivity: Cancelled SaveToDiskTask! (false)
07-11 12:09:11.330 14619 16145 I SaveToDiskTask: No instance found, creating
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: Index 0 requested, with a size of 0
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:468)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.updateInstanceDatabase(SaveToDiskTask.java:198)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.exportData(SaveToDiskTask.java:263)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:125)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:49)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-11 12:09:11.339 14619 16145 E SaveToDiskTask: 	at java.lang.Thread.run(Thread.java:764)
07-11 12:09:11.383 14619 14619 W org.odk.collect.android.activities.FormEntryActivity: Cancelled SaveToDiskTask! (false)
07-11 12:10:26.843 14619 16678 I SaveToDiskTask: No instance found, creating
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: Index 0 requested, with a size of 0
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:468)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.updateInstanceDatabase(SaveToDiskTask.java:198)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.exportData(SaveToDiskTask.java:263)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:125)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at org.odk.collect.android.tasks.SaveToDiskTask.doInBackground(SaveToDiskTask.java:49)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-11 12:10:26.855 14619 16678 E SaveToDiskTask: 	at java.lang.Thread.run(Thread.java:764)
07-11 12:10:26.908 14619 14619 W org.odk.collect.android.activities.FormEntryActivity: Cancelled SaveToDiskTask! (false)
```

**Comment by zestyping** [comment]
"Index 0 requested, with a size of 0" is a message generated by `checkPosition`.  It means that we attempted to read a result from a query (the first row) but zero rows were returned.

**Comment by zestyping** [comment]
This occurs in `SaveToDiskTask`, which is part of ODK.  The URI at this point is the one passed in to `FormEntryActivity`, and the only invocation of `FormEntryActivity` that I see is in our `OdkActivityLauncher`:

        Intent intent = new Intent(callingActivity, FormEntryActivity.class);
        Uri formUri = ContentUris.withAppendedId(FormsProviderAPI.FormsColumns.CONTENT_URI, formId);
        intent.setData(formUri);

**Comment by zestyping** [comment]
I think what this means is that the form definition has disappeared from the local database.  Perhaps a sync operation is deleting it between the time the form is launched and when it is submitted?
