### ISSUE TITLE
Crash: The app on emulator crashes when it is trying to display the red banner at the bottom of the screen

### ISSUE THREAD

**Issue by daisuke-plangrid** [projectbuendia/client#351]
App version:
<img width="171" alt="Screen Shot 2019-06-26 at 3 26 33 PM" src="https://user-images.githubusercontent.com/44586475/60219380-0b2a9f80-9827-11e9-8e67-b6a47b4474a9.png">

I was able to reproduce this by changing the patient's ID to be the exact same as some other patient. Normally it will display the server error. 

Stack trace:
```
2019-06-26 15:32:46.296 9645-9645/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.projectbuendia.client.dev, PID: 9645
    java.lang.ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.NinePatchDrawable
        at org.projectbuendia.client.net.OpenMrsErrorListener.displayErrorMessage(OpenMrsErrorListener.java:119)
        at org.projectbuendia.client.net.OpenMrsServer$3.onErrorResponse(OpenMrsServer.java:155)
        at com.android.volley.Request.deliverError(Request.java:580)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
```

**Comment by saratheneale** [comment]
Note: I can't reproduce on my Samsung actual Tablet. 

@daisuke-plangrid is reproducing this on the emulator. We compared cases and my tablet won't fail.

**Comment by saratheneale** [comment]
Steps to reproduce: 
1. Click existing patient (Ex. `Lei Skywalker ID 70`)
2. Click Edit Button. Click Edit Patient.
3. Change ID to already existing id - (Ex. `60`). 
Result: Crash.

**Comment by daisuke-plangrid** [comment]
I was able to reproduce the crash on @saratheneale's phone. So at this point you get inconsistent behavior on different devices.

**Comment by mjanes** [comment]
I am able to replicate this on emulator. 

After changing the id of a patient, it does take a while before happening.

**Comment by zestyping** [comment]
I can't replicate this on my tablet.  Here's the message I see:

![duplicate-id-message](https://user-images.githubusercontent.com/236086/60255724-21674880-9885-11e9-8b00-359c1999368b.png)
