### ISSUE TITLE
Running Buendia app

### ISSUE THREAD

**Issue by jvanz** [projectbuendia/client#36]
Hi!

I am trying to run the client app on a emulator. In my tests I have tried to use the `dev.projectbuendia.org:9000` (default value) as  server. But when I run the app the following error is shown:

```
09-28 01:11:41.495    3091-3115/org.projectbuendia.client.dev E/Volley﹕ [106] BasicNetwork.performRequest: Unexpected response code 500 for http://dev.projectbuendia.org:9000/openmrs/ws/rest/v1/projectbuendia/user?q=
09-28 01:11:41.635    3091-3091/org.projectbuendia.client.dev D/dalvikvm﹕ GC_FOR_ALLOC freed 524K, 9% free 5968K/6556K, paused 46ms, total 47ms
09-28 01:11:42.095    3091-3133/org.projectbuendia.client.dev E/buendia/UserManager﹕ Load users task failed
    java.util.concurrent.ExecutionException: com.android.volley.VolleyError: Unknown resource: v1/projectbuendia/user
            at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
            at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:88)
            at org.projectbuendia.client.user.UserStore.syncKnownUsers(UserStore.java:105)
            at org.projectbuendia.client.user.UserStore.loadKnownUsers(UserStore.java:70)
            at org.projectbuendia.client.user.UserManager$LoadKnownUsersTask.doInBackground(UserManager.java:275)
            at org.projectbuendia.client.user.UserManager$LoadKnownUsersTask.doInBackground(UserManager.java:266)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: com.android.volley.VolleyError: Unknown resource: v1/projectbuendia/user
            at org.projectbuendia.client.net.OpenMrsServer$1.onErrorResponse(OpenMrsServer.java:110)
            at com.android.volley.Request.deliverError(Request.java:587)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.android.volley.ServerError
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:161)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)
```

As we can see, it seems the server rest api is not compatible with the current dev branch of the client. The app is requesting a resource there is not in the server side. Do I missing some setup step to run the app in the dev environment?

**Comment by jvanz** [comment]
Actually, I've already solved. My bad,  last night I missed myself in the my remotes... xD
After a good night sleep I figured out the problem. ;)

It's up and running here. =]
