### ISSUE TITLE
Crash when searching for patient (bug report attached)

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#54]
Client 809 connected to dev (server release 0.5).

I moved a new patient (9873) from Triage to "ATFC Mina", then pressed search to look for that patient.

It crashed.

I managed to search after the app restarted, so this may be hard to reproduce.

Bug report: https://www.dropbox.com/s/xx2f9u3g0dqovnj/bugreport-2015-10-06-15-35-33.txt?dl=0

**Comment by dancunningham** [comment]
This just happened again.

Can anyone else reproduce it?

**Comment by G1DR4** [comment]
checking

**Comment by llvasconcellos** [comment]
I could not reproduce the error. But analyzing the bug report I found this:

``` java
10-06 15:35:20.325 31566 31566 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415d4d88)
10-06 15:35:20.335 31566 31566 E AndroidRuntime: FATAL EXCEPTION: main
10-06 15:35:20.335 31566 31566 E AndroidRuntime: Process: org.projectbuendia.client.dev, PID: 31566
10-06 15:35:20.335 31566 31566 E AndroidRuntime: java.lang.NullPointerException
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.ui.PatientListTypedCursorAdapter.getGroup(PatientListTypedCursorAdapter.java:120)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.ui.PatientListTypedCursorAdapter.getChildrenCount(PatientListTypedCursorAdapter.java:124)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.widget.ExpandableListConnector.refreshExpGroupMetadataList(ExpandableListConnector.java:563)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.widget.ExpandableListConnector.expandGroup(ExpandableListConnector.java:688)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.widget.ExpandableListView.expandGroup(ExpandableListView.java:748)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.widget.ExpandableListView.expandGroup(ExpandableListView.java:732)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.widgets.GroupedListView.expandAllGroups(GroupedListView.java:70)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.widgets.GroupedListView.access$000(GroupedListView.java:31)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.widgets.GroupedListView$2.onChanged(GroupedListView.java:63)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.widget.BaseExpandableListAdapter.notifyDataSetChanged(BaseExpandableListAdapter.java:56)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.ui.PatientListTypedCursorAdapter$FetchObservationsTask.onPostExecute(PatientListTypedCursorAdapter.java:258)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at org.projectbuendia.client.ui.PatientListTypedCursorAdapter$FetchObservationsTask.onPostExecute(PatientListTypedCursorAdapter.java:250)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.os.AsyncTask.finish(AsyncTask.java:632)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.os.AsyncTask.access$600(AsyncTask.java:177)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:212)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5137)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:515)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
10-06 15:35:20.335 31566 31566 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by llvasconcellos** [comment]
I couldn't reproduce it but I've seeing this error before. I'll keep an eye on it.
