### ISSUE TITLE
Application crashes when 'Add Test Results' action menu is selected on Patient Chart

### ISSUE THREAD

**Issue by viniciusboson** [projectbuendia/client#61]
Steps to reproduce this bug:
On login chart, select an user.
On locations chart, select a location.
On patient list, select a patient.
Then select 'Add Test Results' on action Menu.
The application crashes and restarts on login chart.

``` java
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity: Attempt to invoke virtual method 'int org.javarosa.form.api.FormEntryPrompt.getControlType()' on a null object reference
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.javarosa.form.api.FormEntryPrompt.getControlType()' on a null object reference
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.widgets2.Widget2Factory.create(Widget2Factory.java:52)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.views.ODKView.<init>(ODKView.java:235)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1445)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:34.986 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:    at org.
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity: length=0; index=-1
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity: org.odk.collect.android.exception.JavaRosaException: length=0; index=-1
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.logic.FormController.stepToNextScreenEvent(FormController.java:716)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1462)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)
10-08 17:43:35.013 26145-26145/org.projectbuendia.client.dev E/org.odk.collect.android.activities.FormEntryActivity:     at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1468)

```

**Comment by G1DR4** [comment]
I'm checking

**Comment by G1DR4** [comment]
http://dev.projectbuendia.org:9000/openmrs/ws/rest/v1/projectbuendia/xforms/buendia-form-add_test_results?v=full returns no errors. checking the client

**Comment by G1DR4** [comment]
i'm back working on it

**Comment by llvasconcellos** [comment]
Not happening. It was a server problem.
